// СГЕНЕРИРОВАНО tools/sprite_lab.py — руками не править.
//
// Форма аппаратов задаётся там примитивами, светотень накладывается по единым
// правилам. Поправить спрайт: изменить функцию в sprite_lab.py и запустить
//   python tools/sprite_lab.py --dart
// ignore_for_file: prefer_single_quotes

part of 'still_sprites.dart';


const _banka = PixelSprite([
  '..kkkkkkkkk...',
  '.kNnnnnnnnnk..',
  '.knmmmmmmmmk..',
  '..kGGGGGGGk...',
  '..kGGGGGGGk...',
  '.kGGGGGGGGGk..',
  'kgGhGGGGGgggk.',
  'kgGhGGGGGgggk.',
  'kgGhGGGGGgggk.',
  'kgGhGGGGGgggk.',
  'kgBBBBBBBBBgk.',
  'kgbbwbbbbxxgk.',
  'kgbbwbbbbwxgk.',
  'kgbbwwbbbxxgk.',
  'kgbbwbbbbxxgk.',
  'kgbbwbbbwxxgk.',
  'kgbbwbbbbxxgk.',
  'kgbbwbbbbxxgk.',
  'kgbbwbbwbxxgk.',
  'kgbbwbbbbxxgk.',
  '.kGbwbbbbxgk..',
  '..kkkkkkkkk...',
]);

const _bidon = PixelSprite([
  '.......kkkk.......',
  '.....kkNnnnkk.....',
  '....kNnMMMMnnk....',
  '....knmmmmmmmk....',
  '.....kQpppppk.....',
  '.....kQpppppk.....',
  '.....kQpppppk.....',
  '.....kQpppppk.....',
  '...kkqQpppppPkk...',
  '..kNpqQpppppPPNk..',
  '.kNPpqQpppppPPPNk.',
  'kNkPpqQpppppPPPkNk',
  'knkPpqQpppppPPPknk',
  '.kkPpqQpppppPPPkk.',
  '..kPpqQpppppPPPk..',
  '..kPpqQppppiiPPk..',
  '..kPpqQppppiPPPk..',
  '..kPpqQpppppPPPk..',
  '..kPpqQpppppPPPk..',
  '..kPpqQpppppPPPk..',
  '..kUulLuuuuuUUUk..',
  '..kPpqQpppppPPPk..',
  '..kPpqQpppppPPPk..',
  '...kpqQpppppPPk...',
  '....kkkkkkkkkk....',
]);

const _flyaga = PixelSprite([
  '........kNnnnnnk..kk....',
  '.......kNMMMMMMnkkNnk...',
  '.......knmmmmmmmkknmk...',
  '.......kzvvvvvvvNnMmk...',
  '.......kzvvvvvvvkknmk...',
  '.......kzvvvvvvvk.kk....',
  '.......kzvvvvvvvk.......',
  '.....kkZzvvvvvvvvkk.....',
  '....kvvZzvvvvvvvvVVk....',
  '...kvvvZzvvvvvvvvVVVk...',
  '.kkVvvvZzvvvvvvvvVVVVkk.',
  'kNnVvvvZzvvvvvvvvVVVVNnk',
  'knmVvvvZzvvvvvvvvVVVVnmk',
  'knmVvvvZzvvvvvvvvVVVVnmk',
  '.kkVVVVVVVVVVVVVVVVVVkk.',
  '..kVvvvZzvvvvvvvvVVVVk..',
  '..kVvvvZzvvBvvvvvVVVVk..',
  '..kVvvvZzBBBBBvvvVVVVk..',
  '..kVvvvZzvvBvvvvvVVVVk..',
  '..kVvvvZzvBvBvvvvVVVVk..',
  '..kVvvvZzvvvvvvvvVVVVk..',
  '..kVVVVVVVVVVVVVVVVVVk..',
  '..kVvvvZzvvvvvvvvVVVVk..',
  '..kVvvvZzvvvvvvvvVVVVk..',
  '..kVvvvZzvvvvvvvvVVVVk..',
  '..kVvvvZzvvvvvvvvVVVVk..',
  '..kVvvvZzvvvvvvvvVVVVk..',
  '...kvvvZzvvvvvvvvVVVk...',
  '....kkkkkkkkkkkkkkkk....',
]);

const _dedov = PixelSprite([
  '......kkkkkkkkkkkkkkkk............',
  '.....kCCCCCCCCCCCCCCCCk...........',
  '....kCCCCcccccccccccccCk..........',
  '.....kCCCCkkkkkkkkkkkkCk..........',
  '......kCCk............kCk.........',
  '.....kkCCkk........kkkkkCkkkkk....',
  '...kkCCCCCCkk.....kmnnnnnnnmmmk...',
  '..kCDCCCCCCCck....kmmnmmmmmmmmk...',
  '.kCCDCCCCCCCcck...kmCCCCCCCCCmk...',
  'kcCCDCCCCCCCccck..kmcnnnnnnmcmk...',
  'kcCCDCCCCCCCccck..kmnnmmmmmmmmk...',
  'kcCCDCCCCCqqqcck..kmCCCCCCCCCmk...',
  'kcCCDCCCCCqkqcck..kmcnnnnnnmcmk...',
  'kcCCDCCCCCqqqcck..kmnnmmmmmmmmk...',
  'kcCCDCCCCCCCccck..kmCCCCCCCCCmk...',
  'kcDccDccDccDccck..kmcnnnnnnmcmk...',
  'kcCCDCCCCCCCccck..kmnnMMMMMmmmk...',
  'kcCCDCCCCCCCccck..kmMnMMMMMmmmk...',
  'kcCCDCCCCCCCccck..kmmnmmmmmmCCk...',
  'kcCCDCCCCCCCccck...kkkkkkkkkCCk...',
  'kcCCDCCCCCCCccck..........kkkBkk..',
  'kcCCDCCCCCCCccck.........kGhGGggk.',
  'kcCCDCCCCCCCccck.........kGbbbbgk.',
  '.kkkkkkkkkkkkkk..........kGbbbbgk.',
  '.........................kGbbbbgk.',
]);

const _zmeevik = PixelSprite([
  '......................kk..',
  '...kkkkkkkkkkkkkk....kJjk.',
  '.kkMMNnMMMMMMMMmmkk.kJIk..',
  'kmMMMNnMMMMMMMMmmmmkJIk...',
  'kmmmmmmmmmmmmmmmmmmJIk....',
  'kmMMMNnMMMMMMMMmmmJIk.....',
  'kmMMJjjjjjjjjjjjmmmk......',
  'kmMMCCCCCCCCCCCCmmmk......',
  'kmMMccccccccccccmmmk......',
  'kmMMCJjjjjjjjjjjmmmk......',
  'kmMMCCCCCCCCCCCCmmmk......',
  'kmMMccccccccccccmmmk......',
  'kmMMJjjjjjjjjjjCmmmk......',
  'kmMMCCCCCCCCCCCCmmmk......',
  'kmMMccccccccccccmmmk......',
  'kmMMCJjjjjjjjjjjmmmk......',
  'kmMMCCCCCCCCCCCCmmmk......',
  'kmMMccccccccccccmmmk......',
  'kmMMJjjjjjjjjjjCmmmk......',
  'kmMMCCCCCCCCCCCCmmmk......',
  'kmMMccccccccccccmmmk......',
  'kmMMCJjjjjjjjjjjmmmkkkk...',
  'kmMMCCCCCCCCCCCCmmCCCCCk..',
  'kmMMccccccccccccmmCCCCCk..',
  'kmMMMNnMMMMMMMMCmmmkkCCk..',
  'kmmmmmmmmmmmmmmmmmmkkkBkk.',
  'kmMMMNnMMMMMMMMmmmmGhGGggk',
  '.kJjkkkkkkkkkkkkJjkGbbbbgk',
  '.kjIk..........kjIkGbbbbgk',
  '.kjIk..........kjIkGbbbbgk',
  '.kjIk..........kjIkGbbbbgk',
]);

const _tseh = PixelSprite([
  '......kkkkkkkkkkkkkkkkkkkkkkkkk.......',
  '.....kNnnnnnnnnnnnnnnnnnnnnnnnnk......',
  '.....knkkkkkkkkkkknkkkkkkkkkkknk......',
  '.....knk.......kkknkkk.......knk......',
  '.....knk......kCDCnCCck......knk......',
  '.....knk.....kCCDCnCCcck.....knk......',
  '.....knk.....kCCDCCCCcck.....knk......',
  '.....knk.....kCCDCCCCcck.....knk......',
  '...kkknkkk...kCCDCCCCcck.....knk......',
  '..kCDCnCCck..kccccccccck.....knk......',
  '.kCCDCnCCcck.kCCDCCCCcck.....knk......',
  '.kCCDCCCCcck.kCCDCCCCcck...kkknkkk....',
  '.kCCDCCCCcck.kCCDCCCCcck..kCDCnCCck...',
  '.kCCDCCCCcck.kCCDCCCCcck.kCCDCnCCcck..',
  '.kccccccccck.kccccccccck.kCCDCCCCcck..',
  '.kCCDCCCCcck.kCCDCCCCcck.kCCDCCCCcck..',
  '.kCCDCCCCcck.kCCDCCCCcck.kCCDCCCCcck..',
  '.kCCDCCCCcck.kCCDCCCCcck.kccccccccck..',
  '.kCCDCCCCcck.kCCDCCCCcck.kCCDCCCCcck..',
  '.kccccccccck.kccccccccck.kCCDCCCCcck..',
  '.kCCDbbbCcck.kCCDbbbCcck.kCCDbbbCcck..',
  '.kCCDbwbCcck.kCCDbwbCcck.kCCDbwbCcck..',
  '.kCCDbbbCcck.kCCDbbbCcck.kcccbbbccck..',
  '.kCCDCCCCcck.kCCDCCCCcck.kCCDCCCCcck..',
  '.kccccccccck.kccccccccck.kCCDCCCCcck..',
  '.kCCDCCCCcck.kCCDCCCCcck.kCCDCCCCcck..',
  '.kCCDCCCCcck.kCCDCCCCcck.kCCDCCCCcck..',
  'kkCCDCCCCcckkkCCDCCCCcckkkCCDCCCCcckk.',
  'Jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjk',
  'jiiIIIIIIIIIIIIIIiiiIIIIIIIIIIIIIIiiIk',
  'kjIkkkkkkkkkkkkkkjiIkkkkkkkkkkkkkkjIk.',
  'kjIk............kjiIk............kjIk.',
  'kjIk............kjIIk............kjIk.',
]);

const _podval = PixelSprite([
  '..........kkkkkkkkkkkkk...........',
  '.........keeooeeeeeeeEEk..........',
  '.........keNooeeEeeeeNEk..........',
  '.........kenooeeEeeeenEk..........',
  '.........kenooeeEeeeenEk..........',
  '.........kenooeeEeeeenEk..........',
  '.........kenooeeEeeeenEk..........',
  '........kEenooeeEeeeenEEk.........',
  '.........kenooeeEeeeenEk..........',
  '.........kenooeeEeeeenEk..........',
  '.........kenooeeEeeeenEk..........',
  '.........kenooeDdeeeenEk..........',
  '..kkkkkkkkenooedceeeenEkkkkkkkk...',
  '.keeooeeeEeeooeeeeeeeEEEeeeeeEEk..',
  '.keNooeeEeeeeNEkkkeNooeeEeeeeNEk..',
  '.kenooeeEeeeenEk.kenooeeEeeeenEk..',
  '.kenooeeEeeeenEk.kenooeeEeeeenEk..',
  '.kenooeeEeeeenEk.kenooeeEeeeenEk..',
  '.kenooeeEeeeenEk.kenooeeEeeeenEk..',
  'kEenooeeEeeeenEEkEenooeeEeeeenEEk.',
  '.kenooeeEeeeenEk.kenooeeEeeeenEk..',
  '.kenooeeEeeeenEk.kenooeeEeeeenEk..',
  '.kenooeeEeeeenEk.kenooeeEeeeenEk..',
  '.kenooeDdeeeenEk.kenooeDdeeeenEk..',
  '.kenooedceeeenEk.kenooedceeeenEk..',
  '.keeooeeBeeeeEEk.keeooeeBeeeeEEk..',
]);

const _tsisterna = PixelSprite([
  '....kkkkkkkk..............kkkkk.............',
  '...kLlllllllk............kMMMMMk............',
  '...klLlllluUkkkkkkkkkkkkkkMMMMMkkkkkkkkkkk..',
  '...klllllluUkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk.',
  '..kklllllluUQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQk',
  '.kLlullllluUpppppppppppppppppppppppppppppppk',
  '.kluuuuuuuuUpppppppppppppppppppppppppppppppk',
  '.kluuuuuuuuUpppppppppppppppppppppppppppppppk',
  '.kluuuuuuuuulllllqqqLqqqLqqqLqqqLqqqLqqqLllk',
  '.kluuuuuuuuuuuuuUqLqlqLqlqLqlqLqlqLqlqLqluUp',
  '.kluuuuuuuuuUUUUUqqqlqqqlqqqlqqqlqqqlqqqlUUk',
  '.kluuuuuuuuUpppppppppppppppppppppppppppppppk',
  'kyyluuuuuuuUpppppppppppppppppppppppppppppppk',
  'kyyluuuuuuuUPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPk',
  '.kLuuuuuuuuUPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPk',
  '.kluuuuuuuuUkPPPPPPPPPPPPPPPPPPPPPPPPPPPPPk.',
  'kiiiiiIIIiiiiiiiiiiiiiiiiiiiiIIIiiiiIIIiiiik',
  'kiiiiIIIIIiiiiiiiiiiiiiiiiiiIIIIIiiIIIIIiiik',
  '.kkkIIIMIIIkkkkkkkkkkkkkkkkIIIMIIIIIIMIIIkk.',
  '...kIIMMMIIk..............kIIMMMIIIIMMMIIk..',
  '...kIIIMIIIk..............kIIIMIIIIIIMIIIk..',
  '....kIIIIIk................kIIIIIkkIIIIIk...',
  '.....kIIIk..................kIIIk..kIIIk....',
  '......kkk....................kkk....kkk.....',
]);

const _druzhba = PixelSprite([
  '................kkkkkkkk................',
  '.............kkkTtttttttkkk.............',
  '............kTttrrrrrrrrtttk............',
  '............ktrrrrrrrrrrrrRk............',
  '............ktRRrrrrrrrrRRRk............',
  '..........kk.kkktRRRRRRRkkk..kk.........',
  '.........kiik...kkkMmkkk....kiik........',
  'kkkkkkkkkkiikkkkkkkMmkkkkkkkkiikkkkkkkkk',
  'NNNNNNNNNNiiNNNNNNNMmNNNNNNNNiiNNNNNNNNN',
  'MMMMMMMMMMiiMMMMMMMMmMMMMMqMMiiMMMMMMMMM',
  'MMMMMMMMMMiiMMMMMMMMmMMMMqqTMiiMMMMMMMMM',
  'MMMMMMMMMMiiMMMMMMiMmiMMqqkqqiiMMMMMMMMM',
  'mmmmmmmmmmiimmmmmmiiiimmmqqqmiimmmmmmmmm',
  'mmmmmmmmmmiimmmmmmiiiimmmmqmmiimmmmmmmmm',
  'kkkkkkkkkkiikkkkkkiiiikkkkMkkiikkkkkkkkk',
  '.....kiiikiik....kiiiik..kMkkiikkiiik...',
  'kkkkkkiJikkkkkkkkkiiiikkkkMkkkkkkiJikkkk',
  'NNNNNNiiiNNNNNNNNNiiiiNNNNNNNNNNNiiiNNNN',
  'nnnnnniiinnnnnnnnnnnnnnnnnnnnnnnniiinnnn',
  'MMMMMMiiiMMMMMMMMMMMMMMMMMMMMMMMMiiiMMMM',
  'MMMMMMiiiMMMMMMMMMMMMMMMMMMMMMMMMiiiMMMM',
  'MMMMMMiiiMMMMMMMMMMMMMMMMMMMMMMMMiiiMMMM',
  'MMMMMMiiiMMMMMMMMMMMMMMMMMMMMMMMMiiiMMMM',
  'mmmmmmiiimmmmmmmmmmmmmmmmmmmmmmmmiiimmmm',
  'mmmmmmiiimmmmmmmmmmmmmmmmmmmmmmmmiiimmmm',
  'kkkiikiJikkkkkkkkkkkkkkkkkkkkkkkkiJiiikk',
  '..kiikiiik......................kiiiiik.',
  '..kiikkkk........................kkkiik.',
  '..kiik.............................kiik.',
  '..kiik.............................kiik.',
]);

const _zavod = PixelSprite([
  '............................kkkkkkk...',
  '...........................kTttttttk..',
  '...........................ktrrrrrRk..',
  '............................ktrrrRk...',
  '............................ktrrrRk...',
  '............................ktRRRRk...',
  '............................kqqqqqk...',
  '............................kqqqqqk...',
  '............................kTttttk...',
  '............................ktrrrRk...',
  '............................ktrrrRk...',
  '............................ktrrrRk...',
  '.......k......k......k......ktrrrRk...',
  '.kkkkkkYkkkkkkYkkkkkkYkkkkkkYtrrrRk...',
  'kiiiiiiYiiiiiiYiiiiiiYiiiiiiYtrrrRk...',
  'kiiiiikYiiiiikYiiiiikYiiiiikYtrrrRk...',
  'kiiiikkYiiiikkYiiiikkYiiiikkYtrrrRk...',
  'kiiik.kYiiik.kYiiik.kYiiik.kYtrrrRk...',
  'kiik..kYiik..kYiik..kYiik..kYtrrrRk...',
  'kikkkkkYikkkkkYikkkkkYikkkkkYtrrrRkkk.',
  'kTtttttttttttttttttttttttttttrrrrrtttk',
  'ktrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrRk',
  'ktrRrrrRrrrRrrrRrrrRrrrRrrrRrrrRrrrRRk',
  'ktrrRRRRRrrrRRRRRrrrRRRRRrrrrrrrrrrrRk',
  'kRrRyyiyyRrRyyiyyRrRyyiyyRrrrRrrrRrrRk',
  'ktrRyyiyytrRyyiyytrRyyiyytrrrrrrrrrrRk',
  'ktrRyyiyytrRyyiyytrRyyiyytrRrrrRrrrRRk',
  'ktrRiiiiitrRiiiiitrRiiiiitrrrrrrrrrrRk',
  'kRrRyyiyyRrRyyiyyRrRyyiyyRRRRRRRRRRRRk',
  'ktrRyyiyytrRyyiyytrRyyiyytiiiiiiiiiitk',
  'ktrRyyiyytrRyyiyytrRyyiyytijjjjjjjjitk',
  'ktrrtttttrrrtttttrrrtttttRiiiiiiiiiitk',
  'kRrrrRrrrRrrrRrrrRrrrRrrrRijjjjjjjjitk',
  'ktrrrrrrrrrrrrrrrrrrrrrrrRiiiiiiiiiitk',
  'ktrRrrrRrrrRrrrRrrrRrrrRrRijjjjjjjjitk',
  'ktrrrrrrrrrrrrrrrrrrrrrrrRiiiiiiiiiitk',
  'kRrrrRrrrRrrrRrrrRrrrRrrrRijjjjjjjjitk',
  'ktrrrrrrrrrrrrrrrrrrrrrrrRiiiiiiiiiitk',
  'ktRRRRRRRRRRRRRRRRRRRRRRRRiiiiiiiiiitk',
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
]);

const _tanker = PixelSprite([
  '.....kkTtkk.........................................',
  '....kQqqqqqk........................................',
  '....kqppppPk........................................',
  '...kkqppppPkk.................................k.....',
  '..kQqppppppqqk...............................kyk....',
  '..kqppppppppPk...............................kMk....',
  '..kqPpPpPpPpPk...............................kMk....',
  '..kqyqyqyqyqPk...............................kMk....',
  '..kqqpqpqpqpPk...............................kMk....',
  '..kqPpPpPpPpPk...............................kMk....',
  '..kqyqyqyqyqPk...............................kMk....',
  '..kqqpqpqpqpPkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkMk....',
  '..kqppppppppPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMkkkk.',
  '..kqppppppppPkMMMMMkkMMMMMkkMMMMMkkMMMMMkkkkiiiiiiik',
  '..kqppppppppPkMMMMMkkMMMMMkkMMMMMkkMMMMMk..kiiiiiiik',
  '.kkqPPPPPPPPPkMMMMMkkMMMMMkkMMMMMkkMMMMMkkkkiiiiiiik',
  'kJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJik',
  'kiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiik',
  'kiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiik',
  'kiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiik',
  'kiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiik',
  'kiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiikkk.',
  'kTttttttttttttttttttttttttttttttttttttttttttttttk...',
  '.ktrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrRRkk....',
  '..ktrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrRRkk......',
  '...ktrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrRRkk........',
  '....ktRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkk..........',
  '.....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk............',
]);

const _orbita = PixelSprite([
  '.....................kNnnnk.....................',
  '.....................knmmmk.....................',
  '...................kkkkkkkkkk...................',
  '..................kppppppppppk..................',
  '.................kppppppppppppk.................',
  '.................kPppppppppppPk.................',
  '.................kPpqQpyyppPPPk.................',
  '.kkkkkkkkkkkkkkk.kPpqQyyyypPPPk.kkkkkkkkkkkkkkk.',
  'kUUUUUUUUUUUUUUUkkPpqQpyyppPPPkkUUUUUUUUUUUUUUUk',
  'kULuUuuUuuUuuUuukkPpqQpppppPPPkkULuUuuUuuUuuUuuk',
  'kUuuUuuUuuUuuUuukkPPPPPPPPPPPPkkUuuUuuUuuUuuUuuk',
  'kUuuUuuUuuUuuUuukkPpqQpppppPPPkkUuuUuuUuuUuuUuuk',
  'kUUUUUUUUUUUUUUUkkPcCDCCCCCccPkkUUUUUUUUUUUUUUUk',
  'kUuuUuuUuuUuuUuukkPcCDCCCCCccPkkUuuUuuUuuUuuUuuk',
  'kUuuUuuUuuUuuUuukkPcCDCCCCCccPkkUuuUuuUuuUuuUuuk',
  'kUuuUuuUuuUuuUuukkPcCDCCCCCccPkkUuuUuuUuuUuuUuuk',
  'kUUUUUUUUUUUUUUUkkPcCDCCCCCccPkkUUUUUUUUUUUUUUUk',
  'kUuuUuuUuuUuuUuNnnPcCDCCCCCccPNnnuuUuuUuuUuuUuuk',
  'kUuuUuuUuuUuuUuukkPcCDCCCCCccPkkUuuUuuUuuUuuUuuk',
  'kUuuUuuUuuUuuUuukkPpqQpppppPPPkkUuuUuuUuuUuuUuuk',
  'kUUUUUUUUUUUUUUUkkPPPPPPPPPPPPkkUUUUUUUUUUUUUUUk',
  'kUuuUuuUuuUuuUuukkPpqQpppppPPPkkUuuUuuUuuUuuUuuk',
  'kUuuUuuUuuUuuUuukkPpqQpyyppPPPkkUuuUuuUuuUuuUuuk',
  'kUuuUuuUuuUuuUuukkPpqQyyyypPPPkkUuuUuuUuuUuuUuuk',
  'kUUUUUUUUUUUUUUUkkPpqQpyyppPPPkkUUUUUUUUUUUUUUUk',
  'kUuuUuuUuuUuuUuukkPpqQpppppPPPkkUuuUuuUuuUuuUuuk',
  'kUuuUuuUuuUuuUuukkPpqQpppppPPPkkUuuUuuUuuUuuUuuk',
  '.kkkkkkkkkkkkkkk.kPPPPPPPPPPPPk.kkkkkkkkkkkkkkk.',
  '.................kPpqQpppppPPPk.................',
  '.................kPpqQpppppPPPk.................',
  '.................kPpqQpppppPPPk.................',
  '.................kPppppppppppPk.................',
  '.................kppppppppppppk.................',
  '..................kppppppppppk..................',
  '...................kkkkkkkkkk...................',
]);

const _collider = PixelSprite([
  '.................kMMMMMMMMk.................',
  '.................kMMMyMMMMk.................',
  '.................kMMMMMMMMk.................',
  '..............kkkkMMMMMMMMkkkk..............',
  '...........kkkJjjjMMMMMMMMJjjjkkk...........',
  '.........kkJjjIIIIjjDddJjjIIIIjjjkk.........',
  '.......kkJjIDddyyyyydCcyyyyyyDddjjjkk.......',
  '......kJjIIIdCcyyyyydccJyyyyydCcjIIjjk......',
  '.....kJiIyyydccJjjjjjjjijjjjjdccyyyjijk.....',
  '....kJiIyyyyJjjIIIIIIIIIIIIIIjjjyyyyjIjk....',
  '...kJIIyyyyJiIIkkkkkkkkkkkkkkjIijyyyDddJk...',
  '..kJIDddyJjIIkk..............kkjIjjydCcjjk..',
  '.kJiIdCcJiIkk..................kkjijdccjijk.',
  '.kjIydccjIk......................kjijyyyjIk.',
  'kJiIyyyJIk........................kjIyyyjijk',
  'kjIyyyJIk..........................kjjyyyjIk',
  'kjIDddjIk..........................kjIDddjIk',
  'kjIdCcjIk..........................kjIdCcjIk',
  'kjIdccjIk..........................kjIdccjIk',
  'kjIyyyjIk..........................kjIyyyjIk',
  'kjijyyyjjk........................kJIyyyJiIk',
  '.kjIyDddjjk......................kJIDddyjIk.',
  '.kjijdCcjijkk..................kkJiIdCcJiIk.',
  '..kjIdccyjIjjkk..............kkJjIIydccjIk..',
  '...kjjjyyyyjijjkkkkkkkkkkkkkkJjiIyyyyJjIk...',
  '....kjijyyyyjIIjjjjjjjjjjjjjjIIIyyyyJiIk....',
  '...kJiIijyyyDddjIIIIIIIIIIIIIDddyyyJiIijk...',
  '...kjIkjIjjjdCcyyyyyDdddyyyyydCcJjjIIkjIk...',
  '...kjIkkkjIIdccyyyyydCCcyyyyydccjIIkkkjIk...',
  '...kjIk..kkjjjjjjjjjdCCcJjjjjjjjIkk..kjIk...',
  '...kjIk....kkkjmMMNMdcccMMmmmjkkk....kjIk...',
  '...kjIk.......kmMMNMMMMMMMmmmk.......kjIk...',
  '...kjIk.......kmMbbbbbbbbbbmmk.......kjIk...',
  '...kjIk.......kmMbbbbbbbbbbmmk.......kjIk...',
  '...kjIk.......kmMbbbbbbbbbbmmk.......kjIk...',
  '...kjIk.......kmMbbbbbbbbbbmmk.......kjIk...',
  '...kjIk.......kmMMNMMMMMMMmmmk.......kjIk...',
  '..kkjIkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkjIkk..',
  '.kJjiijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjiijjk.',
  '.kjIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIk.',
]);

/// Палитра, по которой собраны спрайты. Сверяется тестом с генератором.
const Map<String, int> kStillPaletteArgb = {
  'k': 0xFF1A1410,
  's': 0x55000000,
  'c': 0xFF8C5430,
  'C': 0xFFC87941,
  'd': 0xFFE09A5C,
  'D': 0xFFF5C08A,
  'm': 0xFF5E5750,
  'M': 0xFF8E8578,
  'n': 0xFFB3AA9C,
  'N': 0xFFDDD5C7,
  'g': 0xFF3B4A47,
  'G': 0xFF5E7A73,
  'h': 0xFF86A69C,
  'H': 0xFFC4DDD3,
  'x': 0xFFA89060,
  'b': 0xFFD8C48A,
  'B': 0xFFF2E2B8,
  'w': 0xFFFFF6DE,
  'P': 0xFFA89C84,
  'p': 0xFFD9CFB8,
  'q': 0xFFEDE5D2,
  'Q': 0xFFFFFBF0,
  'E': 0xFF4A2F1C,
  'e': 0xFF74502F,
  'o': 0xFF98693F,
  'O': 0xFFB88A55,
  'R': 0xFF6E2A1C,
  'r': 0xFFA8402A,
  't': 0xFFC85A3E,
  'T': 0xFFE68062,
  'I': 0xFF201C19,
  'i': 0xFF38322D,
  'j': 0xFF544C45,
  'J': 0xFF70675E,
  'V': 0xFF363F22,
  'v': 0xFF55603A,
  'z': 0xFF717E4C,
  'Z': 0xFF909C63,
  'U': 0xFF2E4660,
  'u': 0xFF4F7299,
  'l': 0xFF7EA2C8,
  'L': 0xFFB5D0EA,
  'y': 0xFFFFC766,
  'Y': 0xFFFFF0C0,
  '1': 0xFFB8361A,
  '2': 0xFFFF8A00,
  '3': 0xFFFFC766,
  '4': 0xFFFFF3D6,
  'S': 0x55D8D0C0,
};
